language: cpp
os:
  - linux
compiler:
  - gcc
env:
  - PROJECT=NFD
  - PROJECT=NLSR
  # - PROJECT=ndn-tlv-ping
  - PROJECT=ndn-traffic-generator
  - PROJECT=ndns
install:
  - ./deps_ndn-cxx.sh
  - if [[ -f ./deps_${PROJECT}.sh ]]; then ./deps_${PROJECT}.sh; fi
script:
  - ./build_ndn-cxx.sh
  - ./build_${PROJECT}.sh
