language: cpp
os:
  - linux
compiler:
  - gcc
env:
  - PROJECT=NFD
  - PROJECT=NLSR
  - PROJECT=ndn-tlv-ping
  - PROJECT=ndn-traffic-generator
install:
  - ./deps_ndn-cxx.sh
  - ./deps_${PROJECT}.sh
script:
  - ./build_ndn-cxx.sh
  - ./build_${PROJECT}.sh
