dist: bionic
language: cpp
env:
  global:
    - PATCHSET_NDNCXX=master
  matrix:
    - PROJECT=NFD
    - PROJECT=ChronoSync
    - PROJECT=PSync
    - PROJECT=NLSR
    - PROJECT=name-based-access-control
    - PROJECT=ndncert
    - PROJECT=ndns
    - PROJECT=ndn-tools
    - PROJECT=ndn-traffic-generator
    - PROJECT=repo-ng
before_install:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
install:
  - DEPS=$(sort -u ndn-cxx.deps $PROJECT.deps)
  - sudo apt-get update -qq
  - sudo apt-get install -qy $DEPS
before_script:
  - ./build_ndn-cxx.sh
script:
  - ./build_${PROJECT}.sh
