language: cpp
os:
  - linux
compiler:
  - gcc
env:
  - PROJECT=NFD
  - PROJECT=NLSR
  - PROJECT=ndn-tlv-ping
  - PROJECT=ndn-traffic-generator
  - PROJECT=ndns
  - PROJECT=repo-ng
  - PROJECT=ChronoSync
install:
  - ./deps_ndn-cxx.sh
  - if [[ -f ./deps_${PROJECT}.sh ]]; then ./deps_${PROJECT}.sh; fi
before_script:
  - ./build_ndn-cxx.sh
script:
  - ./build_${PROJECT}.sh
