dist: xenial
language: cpp
services:
  - docker
env:
  global:
    - PATCHSET_NDNCXX=master
  matrix:
    - PROJECT=NFD
    - PROJECT=ChronoSync
    - PROJECT=PSync
    - PROJECT=NLSR
    - PROJECT=ndncert
    - PROJECT=ndns
    - PROJECT=ndn-tools
    - PROJECT=ndn-traffic-generator
    - PROJECT=repo-ng
before_install:
  - export PATH=$(echo $PATH | tr ':' '\n' | sed '/\/opt\/python/d' | tr '\n' ':' | sed 's|::|:|g')
install:
  - ./make-Dockerfile.sh
  - docker build -t ndn-cxx-breaks:$TRAVIS_BUILD_ID .
script:
  - docker run ndn-cxx-breaks:$TRAVIS_BUILD_ID bash -c "source patchset.env && ./build_${PROJECT}.sh"
