language: generic
sudo: required
dist: trusty
compiler:
  - gcc
env:
  global:
    - PATCHSET_NDNCXX=master
  matrix:
    - PROJECT=NFD
    - PROJECT=ndn-cxx-integ
    - PROJECT=NLSR
    - PROJECT=ChronoChat
    - PROJECT=ChronoSync
    - PROJECT=ndns
    - PROJECT=repo-ng
    - PROJECT=ndn-tools
    - PROJECT=ndn-traffic-generator
install:
  - ./deps_ndn-cxx.sh
  - if [[ -f ./deps_${PROJECT}.sh ]]; then ./deps_${PROJECT}.sh; fi
before_script:
  - ./build_ndn-cxx.sh
script:
  - ./build_${PROJECT}.sh
