---
sudo: required
services:
  - docker
env:
  global:
    - PATCHSET_NDNCXX=master
  matrix:
    - PROJECT=NFD
    - PROJECT=ndn-cxx-integ
    - PROJECT=NLSR
    - PROJECT=ChronoChat
    - PROJECT=ChronoSync
    - PROJECT=ndns
    - PROJECT=repo-ng
    - PROJECT=ndn-tools
    - PROJECT=ndn-traffic-generator
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
script:
  - ./make-Dockerfile.sh
  - docker build .
